require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module Yorchauth
  RSpec.describe "/users", type: :request do
    include Engine.routes.url_helpers

    # This should return the minimal set of attributes required to create a valid
    # User. As you add validations to User, be sure to
    # adjust the attributes here as well.
    let(:valid_params) { { email: 'user@email.com', password: '123password', password_confirmation: '123password', active: true } }
    let(:invalid_params) { { email: '', password: 's8s', password_confirmation: 'm91' } }

    context 'as the same user' do
      describe "POST /users/create" do
        it 'can create a new account' do
          post users_path, params: { user: valid_params }

          expect(response).to be_successful
        end
      end

      describe "GET /users/:token_id" do
        it "returns success when visiting profile page" do
          user = User.create! valid_params
          post login_path, params: { session: { email: 'user@email.com', password: '123password' } }
          get user_path(user.token_id)

          expect(response).to be_successful
        end
      end

      describe "GET /signup" do
        it "renders a successful response when users are registering" do
          get signup_path

          expect(response).to be_successful
        end
      end

      describe "GET /users/edit/:token_id" do
        it 'return success when editing account' do
          user = User.create! valid_params
          post login_path, params: { session: { email: 'user@email.com', password: '123password' } }
          get edit_user_path(user.token_id)

          expect(response).to be_successful
        end
      end

      describe 'PATCH /users/edit/:token_id' do
        it 'can update user atributtes and update a record' do
          user = User.create! valid_params
          post login_path, params: { session: { email: 'user@email.com', password: '123password' } }
          patch update_user_path(user.token_id), params: { user: { email: 'new@email.com', old_password: '123password' } }
          expect(response).to be_successful
        end
      end
    end
  end
end
